// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Status_screen_init(void)
{
ui_Status = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Status, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Status,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Status, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_StatusPanel = lv_obj_create(ui_Status);
lv_obj_set_width( ui_StatusPanel, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_StatusPanel, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_StatusPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_StatusPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_StatusPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_StatusPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_statusHeader = lv_label_create(ui_StatusPanel);
lv_obj_set_width( ui_statusHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_statusHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_statusHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_statusHeader,"Memory usage");
lv_obj_set_style_text_font(ui_statusHeader, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_statusText = lv_label_create(ui_StatusPanel);
lv_obj_set_width( ui_statusText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_statusText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_statusText, LV_ALIGN_CENTER );
lv_label_set_text(ui_statusText,"this is\nthe status\n");
lv_obj_set_style_text_font(ui_statusText, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_StatusPanel, ui_event_StatusPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Status, ui_event_Status, LV_EVENT_ALL, NULL);

}
