// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: lvgl_altimeter_UI

#if defined(M5UNIFIED)
#include "M5Unified.h"
#else
#include <Arduino.h>
#endif

#include "ui.h"
extern "C"
{
    void clearCountPressed(lv_event_t *e)
    {
        Serial.printf("--->  clearCountPressed \n");
    }
    void mainLoaded(lv_event_t *e)
    {
        Serial.printf("--->  mainLoaded \n");
    }

    void mainUnloadStart(lv_event_t *e)
    {
        Serial.printf("--->  mainUnloadStart \n");
    }

    void initiaFunc(lv_event_t *e)
    {
        Serial.printf("--->  initiaFunc \n");
    }
}