// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: lvgl_altimeter_UI
#include "M5Unified.h"
#include "ui.h"
extern "C"
{
    void clearCountPressed(lv_event_t *e)
    {
        Serial.printf("--->  clearCountPressed \n");
    }
}