// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Params_screen_init(void)
{
ui_Params = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Params, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Params,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Params, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_row(ui_Params, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Params, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_option1 = lv_checkbox_create(ui_Params);
lv_obj_set_width( ui_option1, 100);
lv_obj_set_height( ui_option1, 50);
lv_obj_set_x( ui_option1, -29 );
lv_obj_set_y( ui_option1, 12 );
lv_obj_set_align( ui_option1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_option1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Switch1 = lv_switch_create(ui_Params);
lv_obj_set_width( ui_Switch1, 116);
lv_obj_set_height( ui_Switch1, 51);
lv_obj_set_x( ui_Switch1, -42 );
lv_obj_set_y( ui_Switch1, -63 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );


lv_obj_add_event_cb(ui_option1, ui_event_option1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Params, ui_event_Params, LV_EVENT_ALL, NULL);

}
