// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Status_screen_init(void)
{
ui_Status = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Status, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_StatusText = lv_label_create(ui_Status);
lv_obj_set_width( ui_StatusText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StatusText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StatusText, -104 );
lv_obj_set_y( ui_StatusText, -96 );
lv_obj_set_align( ui_StatusText, LV_ALIGN_CENTER );
lv_label_set_text(ui_StatusText,"StatusText");

ui_Slider1 = lv_slider_create(ui_Status);
lv_obj_set_width( ui_Slider1, 150);
lv_obj_set_height( ui_Slider1, 10);
lv_obj_set_x( ui_Slider1, 238 );
lv_obj_set_y( ui_Slider1, 163 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );


ui_Chart1 = lv_chart_create(ui_Status);
lv_obj_set_width( ui_Chart1, 200);
lv_obj_set_height( ui_Chart1, 100);
lv_obj_set_x( ui_Chart1, -31 );
lv_obj_set_y( ui_Chart1, 8 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);



lv_obj_add_event_cb(ui_Status, ui_event_Status, LV_EVENT_ALL, NULL);

}
