// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main( lv_event_t * e);
lv_obj_t *ui_Main;
lv_obj_t *ui_mainHeader;
lv_obj_t *ui_GPSStatus;
lv_obj_t *ui_SdCardStatus;
lv_obj_t *ui_BLEStatus;
lv_obj_t *ui_WifiStatus;
lv_obj_t *ui_BatteryStatus;
lv_obj_t *ui_mainArea;
lv_obj_t *ui_descriptions;
lv_obj_t *ui_envTempLabel;
lv_obj_t *ui_envelopeHumLabel;
lv_obj_t *ui_outsideTempLabel;
lv_obj_t *ui_outsideHumLabel;
lv_obj_t *ui_values;
lv_obj_t *ui_envTemp;
lv_obj_t *ui_envHum;
lv_obj_t *ui_outsideTemp;
lv_obj_t *ui_outsideHum;


// SCREEN: ui_Status
void ui_Status_screen_init(void);
void ui_event_Status( lv_event_t * e);
lv_obj_t *ui_Status;
lv_obj_t *ui_StatusText;
lv_obj_t *ui_Slider1;
lv_obj_t *ui_Chart1;


// SCREEN: ui_Params
void ui_Params_screen_init(void);
void ui_event_Params( lv_event_t * e);
lv_obj_t *ui_Params;
void ui_event_option1( lv_event_t * e);
lv_obj_t *ui_option1;
void ui_event_Switch1( lv_event_t * e);
lv_obj_t *ui_Switch1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Main( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Status, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Status_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Params, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Params_screen_init);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      mainScreenLoaded( e );
}
}
void ui_event_Status( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Params, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Params_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
}
}
void ui_event_Params( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Status, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Status_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
}
}
void ui_event_option1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      emitEvent( e );
}
}
void ui_event_Switch1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      emitEvent( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Main_screen_init();
ui_Status_screen_init();
ui_Params_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Main);
}
