// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main( lv_event_t * e);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_GPSStatus;
extern lv_obj_t *ui_SdCardStatus;
extern lv_obj_t *ui_BLEStatus;
extern lv_obj_t *ui_WifiStatus;
extern lv_obj_t *ui_BatteryStatus;
void ui_event_TankContainer2( lv_event_t * e);
extern lv_obj_t *ui_TankContainer2;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_tanksChart;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_envTemp;
extern lv_obj_t *ui_envHum;
extern lv_obj_t *ui_outsideTemp;
extern lv_obj_t *ui_outsideHum;
extern lv_obj_t *ui_fuelLiters;
extern lv_obj_t *ui_fuelPct;
// SCREEN: ui_Compass
void ui_Compass_screen_init(void);
void ui_event_Compass( lv_event_t * e);
extern lv_obj_t *ui_Compass;
// SCREEN: ui_GPS
void ui_GPS_screen_init(void);
void ui_event_GPS( lv_event_t * e);
extern lv_obj_t *ui_GPS;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_testLabel;
extern lv_obj_t *ui_TextArea4;
// SCREEN: ui_Parameters
void ui_Parameters_screen_init(void);
void ui_event_Parameters( lv_event_t * e);
extern lv_obj_t *ui_Parameters;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_runCompassAnimation;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_animationSpeed;
// SCREEN: ui_Status
void ui_Status_screen_init(void);
void ui_event_Status( lv_event_t * e);
extern lv_obj_t *ui_Status;
void ui_event_StatusPanel( lv_event_t * e);
extern lv_obj_t *ui_StatusPanel;
extern lv_obj_t *ui_statusHeader;
extern lv_obj_t *ui_statusText;
// SCREEN: ui_Ruuvi
void ui_Ruuvi_screen_init(void);
extern lv_obj_t *ui_Ruuvi;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_ruuviHeader;
extern lv_obj_t *ui_ruuviBody;
extern lv_obj_t *ui_Container3;
void ui_event_Envelope( lv_event_t * e);
extern lv_obj_t *ui_Envelope;
extern lv_obj_t *ui_Label4;
void ui_event_OAT( lv_event_t * e);
extern lv_obj_t *ui_OAT;
extern lv_obj_t *ui_Label5;
void ui_event_Cancel( lv_event_t * e);
extern lv_obj_t *ui_Cancel;
void ui_event_Label6( lv_event_t * e);
extern lv_obj_t *ui_Label6;
// SCREEN: ui_Unit
void ui_Unit_screen_init(void);
extern lv_obj_t *ui_Unit;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_unitHeader;
extern lv_obj_t *ui_unitBody;
extern lv_obj_t *ui_Container5;
void ui_event_UnitSave( lv_event_t * e);
extern lv_obj_t *ui_UnitSave;
extern lv_obj_t *ui_Label1;
void ui_event_UnitCancel( lv_event_t * e);
extern lv_obj_t *ui_UnitCancel;
extern lv_obj_t *ui_Label7;
// SCREEN: ui_Config
void ui_Config_screen_init(void);
void ui_event_Config( lv_event_t * e);
extern lv_obj_t *ui_Config;
extern lv_obj_t *ui_Container6;
void ui_event_configText( lv_event_t * e);
extern lv_obj_t *ui_configText;
extern lv_obj_t *ui_Container7;
void ui_event_wipeConfig( lv_event_t * e);
extern lv_obj_t *ui_wipeConfig;
extern lv_obj_t *ui_Label3;
void ui_event_configCancel( lv_event_t * e);
extern lv_obj_t *ui_configCancel;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
