// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Config_screen_init(void)
{
ui_Config = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Config, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container6 = lv_obj_create(ui_Config);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, lv_pct(100));
lv_obj_set_height( ui_Container6, lv_pct(100));
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_configText = lv_label_create(ui_Container6);
lv_obj_set_width( ui_configText, lv_pct(100));
lv_obj_set_height( ui_configText, lv_pct(80));
lv_obj_set_x( ui_configText, 35 );
lv_obj_set_y( ui_configText, 2 );
lv_obj_set_align( ui_configText, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_configText,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_configText,"");
lv_obj_set_style_text_font(ui_configText, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container7 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, lv_pct(100));
lv_obj_set_height( ui_Container7, lv_pct(20));
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container7, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wipeConfig = lv_btn_create(ui_Container7);
lv_obj_set_width( ui_wipeConfig, lv_pct(30));
lv_obj_set_height( ui_wipeConfig, lv_pct(100));
lv_obj_set_align( ui_wipeConfig, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wipeConfig,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wipeConfig, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_wipeConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wipeConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wipeConfig, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wipeConfig, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_wipeConfig);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Wipe\nConfig");
lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_configCancel = lv_btn_create(ui_Container7);
lv_obj_set_width( ui_configCancel, lv_pct(30));
lv_obj_set_height( ui_configCancel, lv_pct(100));
lv_obj_set_align( ui_configCancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_configCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_configCancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_configCancel);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Cancel");

lv_obj_add_event_cb(ui_configText, ui_event_configText, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wipeConfig, ui_event_wipeConfig, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_configCancel, ui_event_configCancel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Config, ui_event_Config, LV_EVENT_ALL, NULL);

}
