// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void showMemory(lv_event_t * e);
void longPressed(lv_event_t * e);
void setEnvelopeMac(lv_event_t * e);
void setOATMac(lv_event_t * e);
void setUnit(lv_event_t * e);
void wipeConfig(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
