// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_GPS_screen_init(void)
{
ui_GPS = lv_obj_create(NULL);
lv_obj_clear_flag( ui_GPS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TextArea2 = lv_textarea_create(ui_GPS);
lv_obj_set_width( ui_TextArea2, 150);
lv_obj_set_height( ui_TextArea2, 70);
lv_obj_set_x( ui_TextArea2, -40 );
lv_obj_set_y( ui_TextArea2, -60 );
lv_obj_set_align( ui_TextArea2, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea2,"Placeholder...");



ui_TextArea3 = lv_textarea_create(ui_GPS);
lv_obj_set_width( ui_TextArea3, 150);
lv_obj_set_height( ui_TextArea3, 70);
lv_obj_set_x( ui_TextArea3, -39 );
lv_obj_set_y( ui_TextArea3, 46 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea3,"Placeholder...");



lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GPS, ui_event_GPS, LV_EVENT_ALL, NULL);

}
