// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Parameters_screen_init(void)
{
ui_Parameters = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Parameters, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Parameters,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Parameters, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_row(ui_Parameters, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Parameters, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Parameters);
lv_obj_set_width( ui_Panel3, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel4 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel4, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel4, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_runCompassAnimation = lv_checkbox_create(ui_Panel4);
lv_checkbox_set_text(ui_runCompassAnimation,"compass animation");
lv_obj_set_width( ui_runCompassAnimation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_runCompassAnimation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_runCompassAnimation, LV_ALIGN_CENTER );
lv_obj_add_state( ui_runCompassAnimation, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_runCompassAnimation, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_runCompassAnimation, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel5, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel5, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"animation speed");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_animationSpeed = lv_slider_create(ui_Panel5);
lv_slider_set_value( ui_animationSpeed, 30, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_animationSpeed)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_animationSpeed, 23221321, LV_ANIM_OFF);
lv_obj_set_width( ui_animationSpeed, 150);
lv_obj_set_height( ui_animationSpeed, 10);
lv_obj_set_align( ui_animationSpeed, LV_ALIGN_CENTER );


lv_obj_add_event_cb(ui_Parameters, ui_event_Parameters, LV_EVENT_ALL, NULL);

}
