// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Ruuvi_screen_init(void)
{
ui_Ruuvi = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Ruuvi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container1 = lv_obj_create(ui_Ruuvi);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, lv_pct(100));
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ruuviHeader = lv_label_create(ui_Container1);
lv_obj_set_width( ui_ruuviHeader, lv_pct(100));
lv_obj_set_height( ui_ruuviHeader, lv_pct(15));
lv_obj_set_align( ui_ruuviHeader, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_ruuviHeader, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ruuviBody = lv_label_create(ui_Container1);
lv_obj_set_width( ui_ruuviBody, lv_pct(100));
lv_obj_set_height( ui_ruuviBody, lv_pct(65));
lv_obj_set_align( ui_ruuviBody, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_ruuviBody, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, lv_pct(90));
lv_obj_set_height( ui_Container3, lv_pct(20));
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Envelope = lv_btn_create(ui_Container3);
lv_obj_set_width( ui_Envelope, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Envelope, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Envelope, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Envelope, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Envelope, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Envelope);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"use as\nEnvelope");
lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OAT = lv_btn_create(ui_Container3);
lv_obj_set_width( ui_OAT, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_OAT, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_OAT, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OAT, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_OAT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_OAT);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"use as\nOAT");
lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cancel = lv_btn_create(ui_Container3);
lv_obj_set_width( ui_Cancel, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Cancel, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Cancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Cancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Cancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Cancel);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Cancel\n");

lv_obj_add_event_cb(ui_Envelope, ui_event_Envelope, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_OAT, ui_event_OAT, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label6, ui_event_Label6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Cancel, ui_event_Cancel, LV_EVENT_ALL, NULL);

}
