// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Unit_screen_init(void)
{
ui_Unit = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Unit, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container4 = lv_obj_create(ui_Unit);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, lv_pct(100));
lv_obj_set_height( ui_Container4, lv_pct(100));
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_unitHeader = lv_label_create(ui_Container4);
lv_obj_set_width( ui_unitHeader, lv_pct(100));
lv_obj_set_height( ui_unitHeader, lv_pct(15));
lv_obj_set_align( ui_unitHeader, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_unitHeader, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_unitBody = lv_label_create(ui_Container4);
lv_obj_set_width( ui_unitBody, lv_pct(100));
lv_obj_set_height( ui_unitBody, lv_pct(65));
lv_obj_set_align( ui_unitBody, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_unitBody, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_Container4);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, lv_pct(100));
lv_obj_set_height( ui_Container5, lv_pct(20));
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container5, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_unitColor = lv_label_create(ui_Container5);
lv_obj_set_width( ui_unitColor, lv_pct(30));
lv_obj_set_height( ui_unitColor, lv_pct(100));
lv_obj_set_align( ui_unitColor, LV_ALIGN_CENTER );
lv_label_set_text(ui_unitColor,"");

ui_UnitSave = lv_btn_create(ui_Container5);
lv_obj_set_width( ui_UnitSave, lv_pct(30));
lv_obj_set_height( ui_UnitSave, lv_pct(100));
lv_obj_set_align( ui_UnitSave, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_UnitSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_UnitSave, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_UnitSave);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Save");
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UnitCancel = lv_btn_create(ui_Container5);
lv_obj_set_width( ui_UnitCancel, lv_pct(30));
lv_obj_set_height( ui_UnitCancel, lv_pct(100));
lv_obj_set_align( ui_UnitCancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_UnitCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_UnitCancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_UnitCancel);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Cancel");

lv_obj_add_event_cb(ui_UnitSave, ui_event_UnitSave, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_UnitCancel, ui_event_UnitCancel, LV_EVENT_ALL, NULL);

}
