#pragma once

#include <lvgl.h>
// #include <core/lv_event.h>

typedef enum
{
    MSG_PAGE_HOME = _LV_EVENT_LAST + 1,
    MSG_PAGE_PARAMS,
    MSG_PAGE_STATUS,
    MSG_COUNT_RESET,

    MSG_BATTERY_STATUS,
    MSG_TIME_CHANGED,
    MSG_SCARD_STATUS,

    MSG_GPS_FIX,
    MSG_POSITION_UPDATE,
    MSG_ENV_UPDATE,
    MSG_OAT_UPDATE,
    MSG_ALTITUDE_UPDATE,
    MSG_PRESSURE_UPDATE,
    MSG_HEADING_UPDATE,
    MSG_SPEED_UPDATE,

    MSG_WIFI_UNCONFIGURED, //61
    MSG_WIFI_STARTED,
    MSG_WIFI_SCAN_COMPLETE,
    MSG_WIFI_CONNECTED,  //64
    MSG_WIFI_DISCONNECTED,

    MSG_COUNT_CHANGED

} uiEvents_t;
