// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: lvgl_altimeter_UI

#if defined(M5UNIFIED)
#include "M5Unified.h"
#else
#include <Arduino.h>
#endif
#include "Esp.h"
#include "ui.h"

extern "C"
{
    void emitEvent(lv_event_t *e)
    {
        Serial.printf("--->  emitEvent=%d target=%p userdata=0x%x\n", e->code, e->current_target, e->user_data);
        Serial.printf("free heap: %lu\n", ESP.getFreeHeap());
        Serial.printf("used psram: %lu\n", ESP.getPsramSize() - ESP.getFreePsram());
    }
}